apiVersion: v1
kind: Pod
metadata:
    name: client-pod
    labels:
      compoment: web
spec:
  containers:
    - name: client
      image: lfbds/multi-client
      ports:
        - containerPort: 3000
